<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBFqa5zM\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBFqa5zM/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBFqa5zM.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBFqa5zM\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerBFqa5zM\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'BFqa5zM',
    'container.build_id' => '0280de4e',
    'container.build_time' => 1585128124,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBFqa5zM');
